apiVersion: apps/v1
kind: Deployment
metadata:
  name: BinaryCalculatorWebapp
  labels:
    app: BinaryCalculatorWebapp-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: BinaryCalculatorWebapp-app
  template:
    metadata:
      labels:
        app: BinaryCalculatorWebapp-app 
    spec:
      containers:
      - name: BinaryCalculatorWebapp-app
        image: https://wzcsofe3980ulab4.azurecr.io/BinaryCalculatorWebapp:latest
        ports:
        - containerPort: 80
