pipeline {
  environment {
    dockerimagename = "BinaryCalculatorWebapp"
    dockerImage = ""
  }
  agent any
  tools {
    maven 'maven' 
  }
  stages {
    stage ('Init') {
      def dockerHome = tool 'docker'
      env.PATH = "${dockerHome}/bin:${env.PATH}"
      steps {
        sh 'echo "Start of Job"'
        sh 'ls -la'
      }
    }
    stage ('test') {
      steps {
        sh 'mvn clean test -f ./BinaryCalculatorWebapp/pom.xml'
      }
    }
    stage ('build and image') {
      steps {
        sh 'mvn package -DskipTests -f ./BinaryCalculatorWebapp/pom.xml'
        script {
          dockerImage = docker.build dockerimagename
        }
      }
    }
    stage ('push image') {
      environment {
        registryCredential = 'jenkins-acr-creds' 
      }
      steps{
        script {
          docker.withRegistry( 'https://wzcsofe3980ulab4.azurecr.io/BinaryCalculatorWebapp', registryCredential ) {
            dockerImage.push("latest")
          }
        }
      }
    }
    stage ('Deploy to kubernetes') {
      steps {
        script {
          kubernetesDeploy(configs: "deployment.yaml", 
                                         "service.yaml")
        }
      }
    }
  }
}